#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3
CUTTLEFISH_TPL=$4
CUTTEFISH_CONF=$5

## Allocate 10 ports per node
##   .7 - http

NUMBER=${NAME##dev}
MQTTENABLED=yes
MQTTPORT=$((11883 + 10 * $NUMBER))
ADMINPASSWORD=secret
APISECRET=changeme
APIBASEPORT=$((8080 + 10 * $NUMBER))
APIPORT=$(($APIBASEPORT + 8))
APISECPORT=$(($APIBASEPORT + 448))
BASE=$((10000 + 10 * $NUMBER))
WEBPORT=$(($BASE + 8))
HANDOFFPORT=$(($BASE + 9))
NODENAME="iorio$NUMBER@127.0.0.1"

echo "Generating $NAME - node='$NODENAME' handoff=$HANDOFFPORT api=$APIPORT"
sed -e "s/@NODE@/$NODENAME/" \
    -e "s/@APIPORT@/$APIPORT/" \
    -e "s/@APISECPORT@/$APISECPORT/" \
    -e "s/@APISECRET@/$APISECRET/" \
    -e "s/@ADMINPASSWORD@/$ADMINPASSWORD/" \
    -e "s/@MQTTENABLED@/$MQTTENABLED/" \
    -e "s/@MQTTPORT@/$MQTTPORT/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" < $TEMPLATE > $VARFILE

sed -e "s/@NODE@/$NODENAME/" \
    -e "s/@APIPORT@/$APIPORT/" \
    -e "s/@APISECPORT@/$APISECPORT/" \
    -e "s/@APISECRET@/$APISECRET/" \
    -e "s/@ADMINPASSWORD@/$ADMINPASSWORD/" \
    -e "s/@MQTTENABLED@/$MQTTENABLED/" \
    -e "s/@MQTTPORT@/$MQTTPORT/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" < $CUTTLEFISH_TPL > $CUTTEFISH_CONF
