#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3

## Allocate 10 ports per node
##   .7 - http

APISECRET=changeme
APIALGORITHM=hs256
NUMBER=${NAME##dev}
APIBASEPORT=$((8080 + 10 * $NUMBER))
APIPORT=$(($APIBASEPORT + 8))
BASE=$((10000 + 10 * $NUMBER))
WEBPORT=$(($BASE + 8))
HANDOFFPORT=$(($BASE + 9))
NODENAME="iorio$NUMBER@127.0.0.1"

echo "Generating $NAME - node='$NODENAME' http=$WEBPORT handoff=$HANDOFFPORT api=$APIPORT"
sed -e "s/@NODE@/$NODENAME/" \
    -e "s/@WEBPORT@/$WEBPORT/" \
    -e "s/@APIPORT@/$APIPORT/" \
    -e "s/@APISECRET@/$APISECRET/" \
    -e "s/@APIALGORITHM@/$APIALGORITHM/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" < $TEMPLATE > $VARFILE
